# Use a base image
FROM alpine

RUN echo "Building"
RUN ["ls"]
# Set the working directory to /app
#WORKDIR /

# Copy the current directory contents into the container at /app
#ADD docker/magicmq /
#ADD docker/configuration.json /
#ADD web /web

# Make port 80 and 8080 available to the world outside this container
#EXPOSE 80
#EXPOSE 1789

# Define environment variable
#ENV NAME World

# Run magicmq when the container launches
#CMD ["/magicmq", "-f", "configuration.json"]
CMD ["echo","in the container"]